# This is a basic workflow to help you get started with Actions

name: build-and-test

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  # workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    name: Prep, Build, and Test
    # The type of runner that the job will run on
    runs-on: ${{matrix.os}}
  
    # A strategy creates a build matrix for your jobs
    strategy:      
      # Set of different configurations of the virtual environment
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Dependencies
      - name: Windows Dependencies
        if: runner.os == 'Windows'
        run: ./scripts/windows/install-dependencies.bat
      - name: Nix Dependencies
        if: runner.os != 'Windows'
        run: |
          chmod +x ./scripts/osx/install-dependencies.sh
          ./scripts/osx/install-dependencies.sh
      
      # Build
      - name: Windows Build
        if: runner.os == 'Windows'
        run: ./scripts/windows/build.bat
      - name: Nix Build
        if: runner.os != 'Windows'
        run: |
          chmod +x ./scripts/osx/build.sh
          ./scripts/osx/build.sh
      
      # Test
      - name: Windows Test
        if: runner.os == 'Windows'
        run: ./build/tests/Release/helloTest.exe
      - name: Nix Test
        if: runner.os != 'Windows'
        run: ./build/tests/helloTest
